# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.5
docker:
  - image: cimg/postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
      POSTGRES_PASSWORD: password
environment:
  DATABASE_URL: postgres://postgres:password@localhost:5432/test_db # Connection string
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - node/run:
          name: build
          npm-run: build-core
      - node/test:
          name: test
          version: '16.18'
          run-command: test:ci
          docker:
            - image: cimg/postgres:14.0
              environment:
                POSTGRES_PASSWORD: password
          environment:
            DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
          setup:
            - browser-tools/install-browser-tools:
                chrome-version: 114.0.5735.90 # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
            #- browser-tools/install-chrome
            #- browser-tools/install-chromedriver

            - run:
                command: |
                  google-chrome --version
                  chromedriver --version
                name: Check install
          post-steps:
            - codecov/upload
