name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**'

jobs:
  build:
    name: Builds & Tests
    runs-on: ubuntu-latest

    services:
    steps:
      - name: 🌐 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧑‍💻 Setup env
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 install things
        run: npm i

      - name: 🛠️ Build
        run: npm run build

      - name: 👌 Tests
        run: npm run test-latest-typescript-build
